[loc]
server_language = "en-US"

[log]
path = "logs"
format = "log_%(date)s-%(time)s.txt"
level = 1
enabled = false

[net]
tickrate = 30
port = 1212
bindto = "::,0.0.0.0"
max_connections = 100
log_late_msg = false

[game]
hostname = "Blackout Directive"
desc = "TODO"
lobbyenabled = true
soft_max_players = 20
maxplayers = 30
lobbyduration = 300
role_timers = true

[hub]
advertise = false
tags = "lang:ru, lang:en, rp:med, region:eu_e"
server_url = ""
hub_urls = "https://hub.spacestation14.com/"

[infolinks]
discord = "https://discord.gg/8BEPa9JbZ6"
patreon = "https://boosty.to/theshued"
github = "https://github.com/crystallpunk-14/blackout-directive"

[procgen]
preload = false

[gateway]
generator_enabled = false

[shuttle]
arrivals = false
arrivals_planet = false
preload_grids = false
auto_call_time = 0
camera_rotation_locked = true

[admin]
deadmin_on_join = true

[ooc]
show_ooc_patron_color = false
enable_during_round = true

[movement]
mob_pushing = true
